server.port=8082
spring.application.name=product-service

# Database
spring.datasource.url=jdbc:postgresql://localhost:5433/product_db
spring.datasource.username=smartcommerce
spring.datasource.password=smartcommerce123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Keycloak JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/smartcommerce
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/smartcommerce/protocol/openid-connect/certs

# Actuator
management.endpoints.web.exposure.include=health,info

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
