spring.application.name=notification-service
server.port=8084

# RabbitMQ
spring.rabbitmq.addresses=${RABBITMQ_URL}

# Resend
resend.api.key=${RESEND_API_KEY}
resend.from.email=${RESEND_FROM_EMAIL}

# Actuator
management.endpoints.web.exposure.include=health,info
