spring.application.name=notification-service
server.port=8084

# RabbitMQ
spring.rabbitmq.addresses=${RABBITMQ_URL}

# Mail - using Gmail SMTP (we'll configure this next)
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Actuator
management.endpoints.web.exposure.include=health,info
