server.port=${PORT:8081}
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

keycloak.server-url=${KEYCLOAK_URL}
keycloak.realm=${KEYCLOAK_REALM:smartcommerce}
keycloak.client-id=${KEYCLOAK_CLIENT_ID:smartcommerce-backend}
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}
